# Generated by Django 6.0 on 2026-01-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posturl',
        ),
        migrations.AddField(
            model_name='post',
            name='Fposturl',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Ipost_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Lposturl',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
