# Generated by Django 6.0 on 2026-01-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='lntoken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
