# Generated by Django 6.0.1 on 2026-01-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_comment_share_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliatePostAction',
        ),
    ]
