# Generated by Django 6.0 on 2026-01-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_post_post_url_remove_post_posturl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageId', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='pageId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social.pages'),
            preserve_default=False,
        ),
    ]
