# Generated by Django 6.0 on 2026-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_pages_post_pageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='pageName',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='pageId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
