# Generated by Django 6.0.1 on 2026-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_affiliateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
