# Generated by Django 6.0.1 on 2026-01-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_affiliatelogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePostAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('like', 'Like'), ('share', 'Share'), ('comment', 'Comment')], max_length=20)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post')),
            ],
        ),
    ]
