# Generated by Django 6.0 on 2026-01-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.post'),
        ),
    ]
