# Generated by Django 6.0 on 2026-01-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_superadmin_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='posts',
        ),
    ]
