# Generated by Django 6.0 on 2026-01-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_remove_superadmin_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imediaid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
